# Generated by Django 5.1.7 on 2025-04-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_family_childmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='childmember',
            name='name',
            field=models.CharField(default='No Name', max_length=100),
        ),
    ]
