# Generated by Django 5.1.7 on 2025-04-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_family_created_at_family_updated_at_children_helps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_id', models.IntegerField()),
                ('invitation_URL', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.IntegerField(choices=[(0, '保留'), (1, '承認'), (2, '否認')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
