# Generated by Django 5.1.7 on 2025-04-19 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='family_id',
        ),
        migrations.AddField(
            model_name='invitation',
            name='family',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.family'),
        ),
        migrations.AlterField(
            model_name='children',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HelpLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_lists', to='app.children')),
                ('help', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helps_lists', to='app.helps')),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_helps', to='app.children')),
                ('help', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='app.helps')),
            ],
        ),
        migrations.CreateModel(
            name='Reactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_image', models.IntegerField(choices=[(0, '💗'), (1, '😊'), (2, '👍'), (3, '🌸'), (4, '😎')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction', to='app.records')),
            ],
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.IntegerField(choices=[(0, 'おかし'), (1, 'おかね'), (2, 'おねがい')], default=0)),
                ('reward_prize', models.IntegerField(blank=True, null=True)),
                ('reward_detail', models.CharField(editable=False, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('help', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='app.helps')),
            ],
        ),
    ]
