# Generated by Django 5.1.7 on 2025-04-25 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_invitation_family_id_invitation_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='child_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='helplists',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.children'),
        ),
        migrations.AlterField(
            model_name='helplists',
            name='help',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.helps'),
        ),
        migrations.AlterField(
            model_name='helps',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helps', to='app.children'),
        ),
        migrations.AlterField(
            model_name='rewards',
            name='reward_detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
