# Generated by Django 5.1.7 on 2025-04-26 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_children_child_name_alter_helplists_child_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='family_id',
        ),
        migrations.AddField(
            model_name='user',
            name='family',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.family'),
        ),
    ]
