# Generated by Django 5.1.7 on 2025-04-26 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_user_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactions',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='app.records'),
        ),
    ]
