# Generated by Django 5.1.7 on 2025-04-26 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_reactions_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user_name',
        ),
    ]
