# Generated by Django 5.1.7 on 2025-05-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_username_user_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='icon',
            field=models.CharField(choices=[('👦', '男の子'), ('👧', '女の子'), ('🚗', '車'), ('🎀', 'リボン'), ('⭐', '星')], default='⭐', max_length=2),
        ),
    ]
