# Generated by Django 5.1.7 on 2025-05-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_children_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='children',
            name='icon',
            field=models.CharField(choices=[('👦', '👦'), ('👧', '👧'), ('🚗', '🚗'), ('🎀', '🎀'), ('⭐', '⭐')], default='⭐', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
