# Generated by Django 5.1.7 on 2025-05-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_user_is_staff_alter_children_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='relationship',
            field=models.IntegerField(choices=[(0, '母'), (1, '父'), (2, '祖母'), (3, '祖父'), (4, '兄'), (5, '姉'), (6, 'その他')], default='6'),
        ),
    ]
