# Generated by Django 5.1.7 on 2025-05-09 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_user_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='family',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.family'),
        ),
        migrations.AlterField(
            model_name='user',
            name='relationship',
            field=models.IntegerField(choices=[(0, '母'), (1, '父'), (2, '祖母'), (3, '祖父'), (4, '兄'), (5, '姉'), (6, 'その他')], default=6),
        ),
    ]
