# Generated by Django 5.1.7 on 2025-05-11 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_user_family_alter_user_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='helps',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='helps',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helps', to='app.children'),
        ),
    ]
