# Generated by Django 5.1.7 on 2025-05-11 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_helps_is_default_alter_helps_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='icon',
            field=models.CharField(choices=[('👦', '👦'), ('👧', '👧'), ('🚗', '🚗'), ('🎀', '🎀'), ('⭐', '⭐')], default='⭐', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.family'),
        ),
    ]
